<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Attendance extends Model
{
    use HasFactory;

    protected $fillable = [
        'employee_id',
        'date',
        'entering_time',
        'out_time',
        'total_working_time',
        'working_type',
        'status',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($attendance) {
            $attendance->employee_id = auth()->user()->id;
        });
    }

    public function employee()
    {
        return $this->belongsTo(User::class, 'employee_id');
    }
}
