<?php

namespace App\Models;

use App\Enum\LeaveStatus;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Leave extends Model
{
    use HasFactory;

    protected $fillable = [
        'employee_id',
        'type_id',
        'reason',
        'days',
        'start_date',
        'end_date',
        'summary',
        'message',
        'status',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($leave) {
            $leave->employee_id = auth()->user()->id;
            $leave->days = $leave->calculateLeaveDays();
            $leave->status = LeaveStatus::PENDING;
        });

        static::updating(function ($leave) {
            $leave->days = $leave->calculateLeaveDays();
        });
    }

    public function calculateLeaveDays()
    {
        $start_date = $this->start_date;
        $end_date = $this->end_date;
        $days = null;

        if (!$start_date || !$end_date) {
            return null;
        };

        if ($start_date == $end_date) {
            return 1;
        }

        $result = Carbon::parse($end_date)->diff(Carbon::parse($start_date), true);
        $days = $result->d + 1;

        return $days;
    }

    public function employee()
    {
        return $this->belongsTo(User::class, 'employee_id');
    }
}
